server:
  port: 4180
management:
  port: 4181
  add-application-context-header: false

spring:
  profiles.active: test
  application.name: 'api-file'
  mvc.throw-exception-if-no-handler-found: true

logging:
  file: /var/log/yunsoo/api-file.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: false
  environment: test
  storage:
    type: s3
    s3:
      bucket_name: test-yunsoo
