server:
    port: 7080

spring:
    profiles.active: test

---
spring:
    profiles: dev
application:
    appId:

---
spring:
    profiles: test
application:
    appId: 2k4d3xp24wpxxcf4myt

---
spring:
    profiles: pro
application:
    appId: