#shared properties
server:
  port: 7180
management:
  port: 7181
  address: 127.0.0.1

spring:
  profiles.active: local

---
spring:
  profiles: local
  thymeleaf:
    cache: false

yunsoo:
  client:
    api-rabbit:
      baseurl: http://localhost:5080/
