server:
  port: 4380
management:
  port: 4381
  add-application-context-header: false

spring:
  profiles.active: local
  application.name: 'api-di'
  mvc.throw-exception-if-no-handler-found: true
  jpa:
    show_sql: false
    database: MYSQL
    generate_ddl: false

jdbc:
  di:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev-yunsoo-di.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/di?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201609
    initial_size: 1
    min_idle: 1
    max_idle: 5
    test_on_borrow: true
    validation_query: select 1

logging:
  file: /var/log/yunsoo/api-di.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: true
  environment: dev

---
spring:
  profiles: local
  jpa.show_sql: true

logging:
  file: c:/logs/yunsoo/api-di.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  environment: local

---
spring:
  profiles: dev

