spring:
  jpa:
    show_sql: false
    database: MYSQL
    generate_ddl: false

yunsoo:
  environment: dev
  aws:
    region: cn-north-1
    dynamodb:
      endpoint:
    s3:
      bucket_name: dev-yunsoo

jdbc:
  master:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201512
    initial_size: 1
    max_idle: 10
    test_on_borrow: true
    validation_query: select 1
