yunsoo:
    environment: dev
    aws:
        region: cn-north-1
        dynamodb:
            endpoint:
        s3:
            bucket_name: dev-yunsoo

jdbc:
    master:
        driver_class: com.mysql.jdbc.Driver
        url: jdbc:mysql://dev-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: admin201512
        pool_initialsize: 1
        pool_maxidle: 100
    read1:
        driver_class: com.mysql.jdbc.Driver
        url: jdbc:mysql://dev-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: admin201512
        pool_initialsize: 1
        pool_maxidle: 100

hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: false
    package_to_scan: com.yunsoo.data.service.dbmodel
