server:
  port: 4280
management:
  port: 4281
  add-application-context-header: false

spring:
  profiles.active: local
  application.name: 'api-key'
  mvc.throw-exception-if-no-handler-found: true
  jpa:
    show_sql: false
    database: MYSQL
    generate_ddl: false

jdbc:
  key:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201512
    initial_size: 1
    max_idle: 10
    test_on_borrow: true
    validation_query: select 1

logging:
  file: /var/log/yunsoo/api-key.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: true
  environment: dev
  client:
    processor:
      base_url: http://localhost:4080/
    file_api:
      base_url: http://localhost:4180/
  storage:
    dynamodb:
      region: cn-north-1
      table_prefix: dev-

---
spring:
  profiles: local
  jpa.show_sql: true

logging:
  file: c:/logs/yunsoo/api-key.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  environment: local
  client:
    processor:
      base_url: http://dev.yunsu.co:4080/
    file_api:
      base_url: http://dev.yunsu.co:4180/
---
spring:
  profiles: dev

