server:
    port: 8080

multipart.maxFileSize: 20MB
multipart.maxRequestSize: 20MB

spring:
    profiles.active: default
---
spring:
    profiles: default
management:
    port: 8081
    address: 127.0.0.1

logging:
    level:
        org.springframework: 'INFO'
        org.hibernate: 'ERROR'
yunsoo:
    debug: true

AmazonSettings:
    s3_basebucket:  yunsudev
    s3_userbaseurl:  photo/users
    s3_productbaseurl: photo/coms/products
    s3_product_default_image_url: photo/coms/products/ysdefault
    s3_product_key_batch_path: product_key_batches
    s3_message_image_url: photo/coms/messages
    s3_org_image_url: photo/coms/icons
    s3_org_default_image_url: photo/coms/icons/ysdefault

dataServiceSetting:
    message_created_status_id:  1
    message_approved_status_id: 3
    message_delete_status_id: 4
    user_created_status_id: 2
    user_delete_status_id: 5

jdbc:
    master:
        driver_class: com.mysql.jdbc.Driver
        url: jdbc:mysql://yunsoo.czevfdgeevhl.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: admin201512
        pool_initialsize: 1
        pool_maxidle: 100
    read1:
        driver_class: com.mysql.jdbc.Driver
        url: jdbc:mysql://yunsoo.czevfdgeevhl.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: admin201512
        pool_initialsize: 1
        pool_maxidle: 100

---
spring:
    profiles: qa
management:
    port: 8081
    address: 127.0.0.1

logging:
    path: /var/logs
    file: yunsoo-data-api.log
    level:
        org.springframework: 'INFO'
        org.hibernate: 'INFO'
yunsoo:
    debug: false

AmazonSettings:
    s3_basebucket:  yunsudev
    s3_userbaseurl:  photo/users
    s3_productbaseurl: photo/coms/products
    s3_product_default_image_url: photo/coms/products/ysdefault
    s3_product_key_batch_path: product_key_batches
    s3_message_image_url: photo/coms/messages
    s3_org_image_url: photo/coms/icons
    s3_org_default_image_url: photo/coms/icons/ysdefault


dataServiceSetting:
    message_created_status_id:  1
    message_approved_status_id: 3
    message_delete_status_id: 4
    user_created_status_id: 2
    user_delete_status_id: 5
    org_verified_status_id: 1

jdbc:
    master:
        driver_class: com.mysql.jdbc.Driver
        url: jdbc:mysql://yunsootestdb.czevfdgeevhl.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: admin201512
        pool_initialsize: 1
        pool_maxidle: 100
    read1:
        driver_class: com.mysql.jdbc.Driver
        url: jdbc:mysql://yunsootestdb-r1.czevfdgeevhl.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: admin201512
        pool_initialsize: 1
        pool_maxidle: 100
