server:
    port: 8080

spring:
    profiles.active: default
---
spring:
    profiles: default
management:
    port: 8081
    address: 127.0.0.1

yunsoo:
    yunsoo.s3_basebucket:  yunsudev
    yunsoo.s3_userbaseurl:  photo/users
    yunsoo.s3_product_key_batch_path: product_key_batches
    debug: true
---
spring:
    profiles: qa
management:
    port: 8081
    address: 127.0.0.1