server:
  port: 3080
management:
  port: 3081
  address: 127.0.0.1
  add-application-context-header: false

multipart:
  max-file-size: 20MB
  max-request-size: 20MB

spring:
  jpa:
    show_sql: false
    database: MYSQL
    generate_ddl: false
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  file: /var/log/data-api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: false
  environment: test
  aws:
    region: cn-north-1
    s3:
      bucket_name: test-yunsoo

jdbc:
  master:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://test-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201512
    initial_size: 10
    max_idle: 20
    test_on_borrow: true
    validation_query: select 1
