server:
  port: 3080
management:
  port: 3081
  address: 127.0.0.1
  add-application-context-header: false

multipart:
  max-file-size: 20MB
  max-request-size: 20MB

spring:
  profiles.active: local
  application.name: 'data-api'
  mvc.throw-exception-if-no-handler-found: true
  jpa:
    show_sql: true
    database: MYSQL
    generate_ddl: false

yunsoo:
  debug: true
  environment: dev

jdbc:
  master:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201512
    initial_size: 1
    min_idle: 1
    max_idle: 5
    test_on_borrow: true
    validation_query: select 1
    initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
---
spring:
  profiles: local

logging:
  file: c:/logs/yunsoo/data-api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

---
spring:
  profiles: dev

logging:
  file: var/log/yunsoo/data-api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'
