server:
  port: 6080
management:
  port: 6081
  
multipart.maxFileSize: 20MB
multipart.maxRequestSize: 20MB

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: cn-north-1

yunsoo:
  permanent_token:
    expires_minutes: 4320 #three days
  access_token:
    expires_minutes: 60
    hash_salt: lvtHDkfIUxJ2bLWHc0MNztUqCJSVPSJO
  login_token:
    expires_minutes: 5
    hash_salt: nC9UYPUupMaViIG3UBODY7B19IYW6Z0X

spring:
  profiles.active: dev

---
spring:
  profiles: dev

logging:
  file: c:/logs/api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  debug: true
  environment: dev
  client:
    dataapi:
      baseurl: http://localhost:3080/
    processor:
      baseurl: http://localhost:4080/
  product_key_base_url: http://dev.yunsu.co:7080/
  cache:
    type: local

---
spring:
  profiles: test
management:
  port: 6081
  address: 127.0.0.1

logging:
  path: /var/log
  file: api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: true
  environment: test
  client:
    dataapi:
      baseurl: http://localhost:3080/
    processor:
      baseurl: http://localhost:4080/
  product_key_base_url: http://t.m.yunsu.co:9080/
  cache:
    type: elasticache
