server:
  port: 6080
management:
  port: 6081
  address: 127.0.0.1
  
multipart.maxFileSize: 20MB
multipart.maxRequestSize: 20MB

yunsoo:
  debug: true
  environment: dev
  client:
    dataapi:
      baseurl: http://localhost:3080/
    processor:
      baseurl: http://localhost:4080/
  product_key_base_url: http://dev.yunsu.co:7080/
  permanent_token:
    expires_minutes: 4320 #three days
  access_token:
    expires_minutes: 60
    hash_salt: lvtHDkfIUxJ2bLWHc0MNztUqCJSVPSJO
  login_token:
    expires_minutes: 5
    hash_salt: nC9UYPUupMaViIG3UBODY7B19IYW6Z0X

spring:
  profiles.active: local
  mvc:
    throw-exception-if-no-handler-found: true

---
spring:
  profiles: local

logging:
  file: c:/logs/api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  cache:
    type: local

---
spring:
  profiles: dev

logging:
  file: /var/log/api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  cache:
    type: redis
    default_expire_time: 600 #seconds
    redis:
      host: dev-yunsoo-cache.tpcoru.0001.cnn1.cache.amazonaws.com.cn
