server:
  port: 6080
management:
  port: 6081
  address: 127.0.0.1
  add-application-context-header: false

multipart:
  max-file-size: 20MB
  max-request-size: 20MB

yunsoo:
  debug: false
  environment: test
  client:
    dataapi:
      baseurl: http://localhost:3080/
    processor:
      baseurl: http://localhost:4080/
  product_key_base_url: http://t-m.yunsu.co:9080/
  cache:
    type: redis
    redis:
      host: test-yunsoo-cache.tpcoru.0001.cnn1.cache.amazonaws.com.cn
  permanent_token:
    expires_minutes: 4320 #three days
  access_token:
    expires_minutes: 60
    hash_salt: lvtHDkfIUxJ2bLWHc0MNztUqCJSVPSJO
  login_token:
    expires_minutes: 5
    hash_salt: nC9UYPUupMaViIG3UBODY7B19IYW6Z0X
  alipay:
    pid: 2088121812016826
    key: e0opacdva54q9todmujp0vc5pwqlcj10
    account_name: 广州云溯科技有限公司
    email: zhe@yunsu.co
    amount: 0.01
    notify_url: http://test-api.yunsu.co:6080/marketing/alipay/notify
    direct_return_url: http://test-enterprise.yunsu.co:9080/enterprise/brandapplication.html
    direct_notify_url: http://test-api.yunsu.co:6080/payment/brand/alipay/notify

spring:
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  file: /var/log/api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'
