server:
  port: 6080
management:
  port: 6081
  address: 127.0.0.1
  add-application-context-header: false

multipart:
  max-file-size: 20MB
  max-request-size: 20MB

spring:
  profiles.active: test
  application.name: 'api'
  mvc.throw-exception-if-no-handler-found: true

yunsoo:
  debug: false
  environment: test
  client:
    auth_api:
      base_url: http://localhost:6180/
    data_api:
      base_url: http://localhost:3080/
    processor:
      base_url: http://localhost:4080/
    file_api:
      base_url: http://localhost:4180/
    key_api:
      base_url: http://localhost:4280/

  product_key_base_url: https://t-m.yunsu.co:9443/
  cache:
    type: redis
    default_expire_time: 600 #seconds
    redis:
      host: test-yunsoo-cache.tpcoru.0001.cnn1.cache.amazonaws.com.cn
  alipay:
    pid: 2088121812016826
    key: e0opacdva54q9todmujp0vc5pwqlcj10
    account_name: 广州云溯科技有限公司
    email: zhe@yunsu.co
    amount: 0.01
    notify_url: https://test-api.yunsu.co:6443/marketing/alipay/notify
    direct_return_url: https://test-enterprise.yunsu.co:9443/enterprise/brandapplication.html
    direct_notify_url: https://test-api.yunsu.co:6443/payment/brand/alipay/notify
  tinify:
    key: VE7EeYz5AdEmDXXabOj3oHm7Kt_ioDQY
  wechat:
    app_id: wxe3804cb3dff62fe3
    app_secret: 7d553f1bbfbe9f86f973bce5d0ee7852
    refresh_token: true

logging:
  file: /var/log/yunsoo/api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'
