server:
  port: 6080
management:
  port: 6081
  address: 127.0.0.1
  add-application-context-header: false

multipart:
  max-file-size: 20MB
  max-request-size: 20MB

spring:
  profiles.active: local
  application.name: 'api'
  mvc.throw-exception-if-no-handler-found: true

yunsoo:
  debug: true
  environment: dev
  client:
    auth_api:
      base_url: http://localhost:6180/
    data_api:
      base_url: http://localhost:3080/
    processor:
      base_url: http://localhost:4080/
    file_api:
      base_url: http://localhost:4180/
    key_api:
      base_url: http://localhost:4280/

  product_key_base_url: http://dev.yunsu.co:7080/
  alipay:
    pid: 2088121812016826
    key: e0opacdva54q9todmujp0vc5pwqlcj10
    account_name: 广州云溯科技有限公司
    email: zhe@yunsu.co
    amount: 0.01
    notify_url: http://dev.yunsu.co:9080/api/marketing/alipay/notify
    direct_return_url: http://dev.yunsu.co:9080/enterprise/brandapplication.html
    direct_notify_url: http://dev.yunsu.co:9080/api/payment/brand/alipay/notify
  tinify:
    key: VE7EeYz5AdEmDXXabOj3oHm7Kt_ioDQY
  wechat:
     app_id: wxe3804cb3dff62fe3
     app_secret: 7d553f1bbfbe9f86f973bce5d0ee7852
---
spring:
  profiles: local

logging:
  file: c:/logs/yunsoo/api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  environment: local
  client:
    auth_api:
      base_url: http://dev-api.yunsu.co:6180/
    data_api:
      base_url: http://localhost:3080/
    processor:
      base_url: http://dev-api.yunsu.co:4080/
    file_api:
      base_url: http://dev-api.yunsu.co:4180/
    key_api:
      base_url: http://dev-api.yunsu.co:4280/
  cache:
    type: local
  alipay:
    notify_url: http://115.192.221.38:6080/marketing/alipay/notify
    direct_return_url: http://localhost/enterprise/brandapplication.html
    direct_notify_url: http://localhost:6080/payment/brand/alipay/notify

---
spring:
  profiles: dev

logging:
  file: /var/log/yunsoo/api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  cache:
    type: redis
    default_expire_time: 600 #seconds
    redis:
      host: dev-yunsoo-cache.tpcoru.0001.cnn1.cache.amazonaws.com.cn
  alipay:
    notify_url: http://dev.yunsu.co:9080/api/marketing/alipay/notify
    direct_return_url: http://dev.yunsu.co:9080/enterprise/brandapplication.html
    direct_notify_url: http://dev.yunsu.co:9080/api/payment/brand/alipay/notify
