server:
  port: 4080

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: true
      static: cn-north-1

yunsoo:
  debug: true
  processor:
    client:
      dataapi:
        baseurl: http://dataapi:8080/
