server:
  port: 4080
management:
  port: 4081
  address: 127.0.0.1
  add-application-context-header: false

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: cn-north-1

spring:
  profiles.active: local
  mvc:
    throw-exception-if-no-handler-found: true

yunsoo:
  debug: true
  environment: dev
  client:
    dataapi:
      baseurl: http://localhost:3080/
  sqs:
    message:
      delayseconds: 60
    handler:
      max: 5000
      batch: 1000

---
spring:
  profiles: local

logging:
  file: c:/logs/data-api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

---
spring:
  profiles: dev

logging:
  file: /var/log/data-api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'
