server:
    port: 4080
management:
    port: 4081

cloud:
    aws:
        stack:
            auto: false
        region:
            auto: true
            static: cn-north-1

spring:
    profiles.active: default
---
spring:
    profiles: default


yunsoo:
    environment: dev
    debug: true
    processor:
        client:
            dataapi:
                baseurl: http://dataapi:3080/

---
spring:
    profiles: test

yunsoo:
    environment: test
    debug: true
    processor:
        client:
            dataapi:
                baseurl: http://localhost:3080/
