server:
  port: 4080
management:
  port: 4081

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: true
      static: cn-north-1

spring:
  profiles.active: dev

---
spring:
  profiles: dev

management:
  port: 4081
  address: 127.0.0.1

yunsoo:
  debug: true
  environment: dev
  client:
    dataapi:
      baseurl: http://localhost:3080/
  sqs:
    message:
      delayseconds: 60
    handler:
      max: 5000
      batch: 1000

---
spring:
  profiles: test

yunsoo:
  debug: true
  environment: test
  client:
    dataapi:
      baseurl: http://localhost:3080/
  sqs:
    message:
      delayseconds: 60
    handler:
      max: 5000
      batch: 1000
