server:
    port: 4080
management:
    port: 4081
    address: 127.0.0.1

cloud:
    aws:
        stack:
            auto: false
        region:
            auto: true
            static: cn-north-1

spring:
    profiles.active: default
---
spring:
    profiles: default


yunsoo:
    debug: true
    environment: dev
    processor:
        client:
            dataapi:
                baseurl: http://dataapi:8080/

---
spring:
    profiles: qa

yunsoo:
    debug: true
    environment: test
    processor:
        client:
            dataapi:
                baseurl: http://localhost:8080/
