server:
  port: 4080
management:
  port: 4081
  address: 127.0.0.1
  add-application-context-header: false

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: cn-north-1

spring:
  profiles.active: local
  application.name: 'processor'
  mvc.throw-exception-if-no-handler-found: true
  jpa:
    show_sql: false
    database: MYSQL
    generate_ddl: false

yunsoo:
  debug: true
  environment: dev
  client:
    data_api:
      base_url: http://localhost:3080/

jdbc:
  processor:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201512
    initial_size: 1
    max_idle: 10
    test_on_borrow: true
    validation_query: select 1

---
spring:
  profiles: local

yunsoo:
  processor:
    environment: local

logging:
  file: c:/logs/yunsoo/processor.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

---
spring:
  profiles: dev

logging:
  file: /var/log/yunsoo/processor.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'
