server:
  port: 4080

cloud:
  aws:
    region:
      auto: true
      static: cn-north-1

amazon:
    dynamodb:
        region: cn-north-1

yunsoo:
  debug: true

jdbc:
    driver_class: com.mysql.jdbc.Driver
    url: jdbc:mysql://yunsoo.czevfdgeevhl.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201512
    pool_initialsize: 1
    pool_maxidle: 100

hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: false
    hbm2ddl_auto: update
    package_to_scan: com.yunsoo.dbmodel

