server:
  port: 4080
management:
  port: 4081
  address: 127.0.0.1
  add-application-context-header: false

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: cn-north-1

spring:
  profiles.active: test
  application.name: 'processor'
  mvc.throw-exception-if-no-handler-found: true
  jpa:
    show_sql: false
    database: MYSQL
    generate_ddl: false

logging:
  file: /var/log/yunsoo/processor.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: false
  environment: test
  client:
    dataapi:
      baseurl: http://localhost:3080/

jdbc:
  processor:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://test-yunsoo.cquafg9deiuc.rds.cn-north-1.amazonaws.com.cn:3306/yunsoo2015DB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin201512
    initial_size: 10
    max_idle: 20
    test_on_borrow: true
    validation_query: select 1
