server:
  port: 5080
management:
  port: 5081

multipart.maxFileSize: 10MB
multipart.maxRequestSize: 10MB

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: cn-north-1

spring:
  profiles.active: dev
  mvc:
    throw-exception-if-no-handler-found: true

---
spring:
  profiles: dev

logging:
  file: c:/logs/api-rabbit.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  debug: true
  environment: dev
  client:
    dataapi:
      baseurl: http://localhost:3080/
  access_token:
    expires_minutes: 5256000
    hash_salt: CGicLqNpyxpGEpDLI3UtWCzgfwczfZqU
  cache:
    type: local

---
spring:
  profiles: test
management:
  port: 5081
  address: 127.0.0.1

logging:
  path: /var/log
  file: api-rabbit.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: true
  environment: test
  client:
    dataapi:
      baseurl: http://localhost:3080/
  access_token:
    expires_minutes: 5256000
    hash_salt: CGicLqNpyxpGEpDLI3UtWCzgfwczfZqU
  cache:
    type: elasticache
