server:
  port: 5080
management:
  port: 5081

multipart.maxFileSize: 10MB
multipart.maxRequestSize: 10MB

spring:
  profiles.active: dev
---
spring:
  profiles: dev

logging:
#    file: c:/logs/yunsoo-api.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  debug: true
  client:
    dataapi:
      baseurl: http://localhost:3080/
  access_token:
    expires_minutes: 5256000
    hash_salt: CGicLqNpyxpGEpDLI3UtWCzgfwczfZqU

---
spring:
  profiles: test
management:
  port: 5081
  address: 127.0.0.1

logging:
  path: /var/log
  file: yunsoo-api-rabbit.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'INFO'

yunsoo:
  debug: true
  client:
    dataapi:
      baseurl: http://localhost:3080/
  access_token:
    expires_minutes: 5256000
    hash_salt: CGicLqNpyxpGEpDLI3UtWCzgfwczfZqU
