server:
  port: 5080
management:
  port: 5081
  address: 127.0.0.1
  add-application-context-header: false

multipart:
  max-file-size: 4MB
  max-request-size: 4MB

spring:
  profiles.active: local
  application.name: 'api-rabbit'
  mvc.throw-exception-if-no-handler-found: true

yunsoo:
  debug: true
  environment: dev
  client:
    auth_api:
      base_url: http://dev.yunsu.co/api/auth/
      system_account_access_token: IGHXxgXYIO3yaWb3zvWgZW1smloFu42snAB0lG9KRDV8MW40NzF0NnBrLDAwMTAwMDAwMDAwMDAwMDAwMDAsMmswcjFsNTVpMnJzNTU0NHd6NQ
    data_api:
      base_url: http://dev-api.yunsu.co:3080/
    file_api:
      base_url: http://dev-api.yunsu.co:4180/
    key_api:
      base_url: http://dev-api.yunsu.co:4280/
    third_api:
      base_url: http://dev-api.yunsu.co:4480/
  access_token:
    expires_minutes: 5256000
    hash_salt: CGicLqNpyxpGEpDLI3UtWCzgfwczfZqU
  wechat:
    redpack_url: http://dev-api.yunsu.co:4480/wechat/redpack

---
spring:
  profiles: local

logging:
  file: c:/logs/yunsoo/api-rabbit.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'
    springfox.documentation: 'ERROR'

yunsoo:
  client:
    auth_api:
      base_url: http://dev.yunsu.co/api/auth
      system_account_access_token: IGHXxgXYIO3yaWb3zvWgZW1smloFu42snAB0lG9KRDV8MW40NzF0NnBrLDAwMTAwMDAwMDAwMDAwMDAwMDAsMmswcjFsNTVpMnJzNTU0NHd6NQ
    data_api:
      base_url: http://dev-api.yunsu.co:3080/
    file_api:
      base_url: http://dev-api.yunsu.co:4180/
    key_api:
      base_url: http://dev-api.yunsu.co:4280/
  cache.type: local
  wechat:
    redpack_url: http://dev-api.yunsu.co:4480/wechat/redpack


---
spring:
  profiles: dev

logging:
  file: /var/log/yunsoo/api-rabbit.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'
    springfox.documentation: 'ERROR'

yunsoo:
  cache:
    type: redis
    default_expire_time: 600 #seconds
    redis:
      host: dev-yunsoo-cache.tpcoru.0001.cnn1.cache.amazonaws.com.cn
