server:
    port: 6088
management:
    port: 6089

multipart.maxFileSize: 10MB
multipart.maxRequestSize: 10MB

spring:
    profiles.active: dev
---
spring:
    profiles: dev

logging:
#    file: c:/logs/yunsoo-api.log
    level:
        org.springframework: 'INFO'
        org.hibernate: 'ERROR'

yunsoo:
    debug: true
    client:
        dataapi:
            baseurl: http://localhost:3080/
    #token secret issued to client who can consume our Business API
    token_secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==

---
spring:
    profiles: test
management:
    port: 6089
    address: 127.0.0.1

logging:
    path: /var/log
    file: yunsoo-api-rabbit.log
    level:
        org.springframework: 'INFO'
        org.hibernate: 'INFO'

yunsoo:
    debug: true
    client:
        dataapi:
            baseurl: http://localhost:3080/
    #token secret issued to client who can consume our Business API
    token_secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==
