server:
  port: 5080
management:
  port: 5081
  address: 127.0.0.1

multipart.maxFileSize: 10MB
multipart.maxRequestSize: 10MB

spring:
  profiles.active: local
  mvc:
    throw-exception-if-no-handler-found: true

yunsoo:
  debug: true
  environment: dev
  client:
    dataapi:
      baseurl: http://localhost:3080/
  access_token:
    expires_minutes: 5256000
    hash_salt: CGicLqNpyxpGEpDLI3UtWCzgfwczfZqU

---
spring:
  profiles: local

logging:
  file: c:/logs/api-rabbit.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  cache:
    type: local

---
spring:
  profiles: dev

logging:
  file: /var/log/api-rabbit.log
  level:
    org.springframework: 'INFO'
    org.hibernate: 'ERROR'

yunsoo:
  cache:
    type: redis
    default_expire_time: 600 #seconds
    redis:
      host: dev-yunsoo-cache.tpcoru.0001.cnn1.cache.amazonaws.com.cn
